### ISSUE TITLE
Broken since Django 1.8

### ISSUE THREAD

**Issue by Mibou** [incuna/django-boolean-sum#1]
Since django commit https://github.com/django/django/commit/f59fd15c4928caf3dfcbd50f6ab47be409a43b01 , _patch_aggregate behaviour as changed and function must be None.

**Comment by Mibou** [comment]
Fixed in PR #2 . Could you please merge ?

**Comment by horva** [comment]
+1

**Comment by Mibou** [comment]
Thank you, issue closed !
